name: Mirror Google Sheets to /public/data

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # каждые 30 минут (можешь поменять)

permissions:
  contents: write            # обязательно: право коммитить в репозиторий

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make data dir
        run: mkdir -p public/data

      # Ссылки на опубликованные CSV (Publish to the web), нужны ИМЕННО такие, чтобы curl видел 200, а не 307/404
      # Подставь свои gid при необходимости
      - name: Download CSVs (follow redirects)
        run: |
          set -euo pipefail

          BASE="https://docs.google.com/spreadsheets/d/e/2PACX-1vSSoiSE1ZmtEo4JQOEIHiJWWTjiG_cV1s7rtcjuUYmbafvuDV1k1_53Q6p-L0f8Qg/pub"

          # токарные
          curl -fsSL -o public/data/lathe.csv   "${BASE}?gid=1008569495&single=true&output=csv"
          # фрезерные
          curl -fsSL -o public/data/milling.csv "${BASE}?gid=361418967&single=true&output=csv"

          # простая валидация: файлы не пустые
          test -s public/data/lathe.csv
          test -s public/data/milling.csv

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): refresh mirrored CSV"
          file_pattern: public/data/*.csv
